//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/输入系统/PlayerControllerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControllerAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControllerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControllerAction"",
    ""maps"": [
        {
            ""name"": ""PlayerNormal"",
            ""id"": ""52a36cc9-8c7e-4db4-b0af-412764a266fb"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""f1c9ca7a-373c-42ba-8b9a-cd4949f7bd70"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5ee5bc3b-8898-4406-91b6-5a1bbcc53622"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""dc23fb7f-ac5e-4cd4-b4e7-28673f257c61"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d6dd817b-3f2e-4c40-bf3d-bd44fa624054"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""29095af9-8a10-4b4e-aacf-b6273984a9e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""759ffba5-8202-4322-b57b-95a8322f742c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerDialog"",
            ""id"": ""ce28af25-9382-4344-adcd-b1a8a314e30f"",
            ""actions"": [
                {
                    ""name"": ""StartDialog"",
                    ""type"": ""Button"",
                    ""id"": ""7defa57b-4396-456a-8e5c-f6e42a669311"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1a1806fa-3afc-496d-a96c-c8bad390252b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerNormal
        m_PlayerNormal = asset.FindActionMap("PlayerNormal", throwIfNotFound: true);
        m_PlayerNormal_Move = m_PlayerNormal.FindAction("Move", throwIfNotFound: true);
        // PlayerDialog
        m_PlayerDialog = asset.FindActionMap("PlayerDialog", throwIfNotFound: true);
        m_PlayerDialog_StartDialog = m_PlayerDialog.FindAction("StartDialog", throwIfNotFound: true);
    }

    ~@PlayerControllerAction()
    {
        UnityEngine.Debug.Assert(!m_PlayerNormal.enabled, "This will cause a leak and performance issues, PlayerControllerAction.PlayerNormal.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerDialog.enabled, "This will cause a leak and performance issues, PlayerControllerAction.PlayerDialog.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerNormal
    private readonly InputActionMap m_PlayerNormal;
    private List<IPlayerNormalActions> m_PlayerNormalActionsCallbackInterfaces = new List<IPlayerNormalActions>();
    private readonly InputAction m_PlayerNormal_Move;
    public struct PlayerNormalActions
    {
        private @PlayerControllerAction m_Wrapper;
        public PlayerNormalActions(@PlayerControllerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerNormal_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerNormal; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerNormalActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerNormalActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerNormalActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerNormalActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerNormalActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerNormalActions instance)
        {
            if (m_Wrapper.m_PlayerNormalActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerNormalActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerNormalActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerNormalActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerNormalActions @PlayerNormal => new PlayerNormalActions(this);

    // PlayerDialog
    private readonly InputActionMap m_PlayerDialog;
    private List<IPlayerDialogActions> m_PlayerDialogActionsCallbackInterfaces = new List<IPlayerDialogActions>();
    private readonly InputAction m_PlayerDialog_StartDialog;
    public struct PlayerDialogActions
    {
        private @PlayerControllerAction m_Wrapper;
        public PlayerDialogActions(@PlayerControllerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @StartDialog => m_Wrapper.m_PlayerDialog_StartDialog;
        public InputActionMap Get() { return m_Wrapper.m_PlayerDialog; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerDialogActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerDialogActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerDialogActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerDialogActionsCallbackInterfaces.Add(instance);
            @StartDialog.started += instance.OnStartDialog;
            @StartDialog.performed += instance.OnStartDialog;
            @StartDialog.canceled += instance.OnStartDialog;
        }

        private void UnregisterCallbacks(IPlayerDialogActions instance)
        {
            @StartDialog.started -= instance.OnStartDialog;
            @StartDialog.performed -= instance.OnStartDialog;
            @StartDialog.canceled -= instance.OnStartDialog;
        }

        public void RemoveCallbacks(IPlayerDialogActions instance)
        {
            if (m_Wrapper.m_PlayerDialogActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerDialogActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerDialogActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerDialogActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerDialogActions @PlayerDialog => new PlayerDialogActions(this);
    public interface IPlayerNormalActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IPlayerDialogActions
    {
        void OnStartDialog(InputAction.CallbackContext context);
    }
}
